# Generated by Django 4.2.1 on 2023-06-02 20:40

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('catagory_name', models.CharField(max_length=50)),
                ('catagory_descriptions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=25)),
                ('comment', models.TextField(max_length=1000)),
                ('is_reaplied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quate', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SubCatagory',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('sub_catagory_image', models.ImageField(upload_to='subcatagory')),
                ('sub_catagory_name', models.CharField(max_length=50)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.catagory')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.SlugField(max_length=250, primary_key=True, serialize=False)),
                ('topic_image', models.ImageField(blank=True, null=True, upload_to='topic')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=25)),
                ('date_created', models.DateField(default=datetime.datetime.today)),
                ('read_times', models.BigIntegerField(blank=True, default=0, null=True)),
                ('blog_post', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('sub_catagory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.subcatagory')),
            ],
        ),
        migrations.CreateModel(
            name='CommentReaply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=25)),
                ('reaply', models.TextField(max_length=1000)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.topic'),
        ),
    ]
