# Generated by Django 4.2.1 on 2023-06-02 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=250)),
                ('descroption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_university', models.CharField(max_length=150)),
                ('start_and_end_year_of_university', models.CharField(max_length=50)),
                ('name_of_depertment', models.CharField(max_length=50)),
                ('type_of_degree', models.CharField(max_length=25)),
                ('desc_of_university', models.CharField(max_length=300)),
                ('uni_link', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='KnownLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=25)),
                ('known_parcent', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_skill', models.CharField(max_length=250)),
                ('known_parcent', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=50)),
                ('youtube', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_company', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=15)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='about_me')),
                ('name', models.CharField(max_length=100)),
                ('locations', models.CharField(max_length=100)),
                ('occupation', models.CharField(default='Blogger', max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('description', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='about.description')),
                ('education', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='about.education')),
                ('languages', models.ManyToManyField(to='about.knownlanguage')),
                ('skills', models.ManyToManyField(to='about.skills')),
                ('work_experience', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='about.workexperience')),
            ],
        ),
    ]
